import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import test from 'node:test';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { generatePostOgpPng } from '../dist/index.js';
import { layoutPostOgpTitle } from '../dist/title-layout.js';

function readPngSize(buffer) {
  return {
    width: buffer.readUInt32BE(16),
    height: buffer.readUInt32BE(20),
  };
}

test('generates a PNG for a short title', async () => {
  const png = Buffer.from(
    await generatePostOgpPng({
      title: 'About',
      category: 'Other',
      publishedAt: new Date('2020-11-23T00:00:00.000Z'),
    }),
  );

  assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
  assert.deepEqual(readPngSize(png), { width: 1200, height: 630 });
});

test('supports long Japanese titles without exceeding three lines', async () => {
  const png = Buffer.from(
    await generatePostOgpPng({
      title: 'SvelteKitで作るGitHubコントリビューター表示コンポーネント',
      category: 'Tech',
      publishedAt: new Date('2025-06-24T12:00:00.000Z'),
    }),
  );

  assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
  assert.deepEqual(readPngSize(png), { width: 1200, height: 630 });
});

test('does not reuse a post OGP cache generated by the legacy v1 schema', async (t) => {
  const cacheDir = await mkdtemp(path.join(tmpdir(), 'og-image-generator-'));
  t.after(() => rm(cacheDir, { recursive: true, force: true }));

  await writeFile(
    path.join(cacheDir, '5df710493250ad52284902c8cbf39564f0a5850f1d5aecfa435b63ac9300f516.png'),
    Buffer.from('legacy v1 sentinel'),
  );

  const png = Buffer.from(
    await generatePostOgpPng(
      {
        title: 'DEV-17 cache invalidation probe',
        category: 'Tech',
        publishedAt: '2026-08-24T00:00:00.000Z',
      },
      { cacheDir },
    ),
  );

  assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
  assert.deepEqual(readPngSize(png), { width: 1200, height: 630 });
});

test('balances Japanese title lines to avoid orphaned kana', () => {
  const layout = layoutPostOgpTitle('基本週2回しかトレーニング出来ない場合のメニュー案');

  assert.deepEqual(layout.lines, ['基本週2回しかトレーニング', '出来ない場合のメニュー案']);
  assert.equal(layout.truncated, false);
});

test('consumes consecutive prohibited-start characters when adjusting line breaks', () => {
  const layout = layoutPostOgpTitle('かてく）』?】、』】ちおおあちうせ');

  assert.ok(
    layout.lines.every(
      (line) => !/^[、。，．・：；！？!?\])）｝」』】〉》ぁぃぅぇぉっゃゅょー…]/.test(line),
    ),
  );
});

test('adds an ellipsis once the title exceeds the three-line budget', () => {
  const layout = layoutPostOgpTitle(
    'これは非常に長い記事タイトルであり、三行に収まりきらないケースをテストするためにさらに文字数を増やしています。最終的には省略記号が付与される必要があります。',
  );

  assert.equal(layout.lines.length, 3);
  assert.equal(layout.truncated, true);
  assert.match(layout.lines.at(-1) ?? '', /…$/);
  assert.ok(
    layout.lines.every(
      (line) => !/^[、。，．・：；！？!?\])）｝」』】〉》ぁぃぅぇぉっゃゅょー…]/.test(line),
    ),
  );
});
