import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import test from 'node:test';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { generatePostOgpPng } from '../dist/index.js';
import {
  getPostOgpTitleStyle,
  layoutPostOgpTitle,
  POST_OGP_TITLE_WIDTH,
} from '../dist/title-layout.js';
import { createElement as h } from 'react';
import satori from 'satori';
import { Resvg } from '@resvg/resvg-js';

const fonts = [
  {
    name: 'Noto Sans JP',
    weight: 700,
    data: await readFile(new URL('../assets/NotoSansJP-Bold.otf', import.meta.url)),
  },
];

async function renderTitle(title) {
  const layout = await layoutPostOgpTitle(title, fonts);
  const lines = new Map();
  const svg = await satori(
    h('div', { lang: 'ja-JP', style: getPostOgpTitleStyle(layout.fontSize) }, layout.title),
    { width: POST_OGP_TITLE_WIDTH, fonts, embedFont: false },
  );
  const ink = new Resvg(
    await satori(
      h('div', { lang: 'ja-JP', style: getPostOgpTitleStyle(layout.fontSize) }, layout.title),
      { width: POST_OGP_TITLE_WIDTH, fonts },
    ),
  ).innerBBox();
  assert.ok(
    ink.x >= 0 && ink.x + ink.width <= POST_OGP_TITLE_WIDTH,
    `${title}: ink exceeds the title width`,
  );
  for (const [, attributes, text] of svg.matchAll(/<text ([^>]*)>(.*?)<\/text>/gs)) {
    const attr = (name) => Number(attributes.match(new RegExp(`${name}="([^"]*)"`))?.[1]);
    const x = attr('x');
    const right = x + attr('width');
    const y = attr('y');
    const line = lines.get(y) ?? { text: '', width: 0 };
    line.text += text;
    line.width = Math.max(line.width, right);
    lines.set(y, line);
  }
  return { layout, lines: [...lines.values()] };
}

function readPngSize(buffer) {
  return {
    width: buffer.readUInt32BE(16),
    height: buffer.readUInt32BE(20),
  };
}

test('generates a PNG for a short title', async () => {
  const png = Buffer.from(
    await generatePostOgpPng({
      title: 'About',
      category: 'Other',
      publishedAt: new Date('2020-11-23T00:00:00.000Z'),
    }),
  );

  assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
  assert.deepEqual(readPngSize(png), { width: 1200, height: 630 });
});

test('supports long Japanese titles without exceeding three lines', async () => {
  const png = Buffer.from(
    await generatePostOgpPng({
      title: 'SvelteKitで作るGitHubコントリビューター表示コンポーネント',
      category: 'Tech',
      publishedAt: new Date('2025-06-24T12:00:00.000Z'),
    }),
  );

  assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
  assert.deepEqual(readPngSize(png), { width: 1200, height: 630 });
});

test('changing the avatar renders a different image and invalidates the cache', async (t) => {
  const cacheDir = await mkdtemp(path.join(tmpdir(), 'og-image-avatar-'));
  t.after(() => rm(cacheDir, { recursive: true, force: true }));
  const render = (color) =>
    generatePostOgpPng(
      {
        title: 'About',
        category: 'Other',
        publishedAt: '2020-11-23',
        avatarDataUrl: `data:image/svg+xml;base64,${Buffer.from(
          `<svg xmlns="http://www.w3.org/2000/svg" width="76" height="76"><rect width="76" height="76" fill="${color}"/></svg>`,
        ).toString('base64')}`,
      },
      { cacheDir },
    );

  const first = Buffer.from(await render('red'));
  assert.deepEqual(Buffer.from(await render('red')), first);
  assert.notDeepEqual(Buffer.from(await render('blue')), first);
  assert.equal((await readdir(cacheDir)).length, 2);
});

test('does not reuse a post OGP cache generated by the legacy v1 schema', async (t) => {
  const cacheDir = await mkdtemp(path.join(tmpdir(), 'og-image-generator-'));
  t.after(() => rm(cacheDir, { recursive: true, force: true }));

  await writeFile(
    path.join(cacheDir, '5df710493250ad52284902c8cbf39564f0a5850f1d5aecfa435b63ac9300f516.png'),
    Buffer.from('legacy v1 sentinel'),
  );

  const png = Buffer.from(
    await generatePostOgpPng(
      {
        title: 'DEV-17 cache invalidation probe',
        category: 'Tech',
        publishedAt: '2026-08-24T00:00:00.000Z',
      },
      { cacheDir },
    ),
  );

  assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
  assert.deepEqual(readPngSize(png), { width: 1200, height: 630 });
});

test('uses actual font widths for Japanese, numbers, mixed text, and unbroken ASCII', async () => {
  for (const title of [
    'あ'.repeat(26),
    '1234567890'.repeat(4),
    '決算紹介 | Old Dominion Freight Line (ODFL) 2021Q2',
    'レビュー：NOVEL ARMS 3X TACTICAL MAGNIFIER',
    '決算紹介 | IDEXX Laboratories (IDXX) 2021Q2',
    'SvelteKitで作るGitHubコントリビューター表示コンポーネント',
    'Supercalifragilisticexpialidocious'.repeat(2),
  ]) {
    const { layout, lines } = await renderTitle(title);
    assert.equal(layout.fontSize, 76, title);
    assert.equal(layout.truncated, false, title);
    assert.ok(lines.length <= 3, title);
    if (/^(あ|123)/.test(title)) {
      assert.equal(lines.length, 2);
      assert.ok(lines[0].width > POST_OGP_TITLE_WIDTH * 0.95);
      assert.equal(lines.map((line) => line.text).join(''), title);
    }
  }
});

test('respects Japanese line-break prohibitions and clamps very long titles to three lines', async () => {
  for (const title of [
    'かてく）』?】、』】ちおおあちうせ',
    '【STEYR L9A2】マガジンキャッチを簡単に左利き用に変更する方法',
    'これは非常に長い記事タイトルであり、三行に収まりきらないケースをテストするためにさらに文字数を増やしています。最終的には省略記号が付与される必要があります。',
  ]) {
    const { layout, lines } = await renderTitle(title);
    assert.ok(lines.length <= 3);
    assert.ok(
      lines.every(
        (line) => !/^[、。，．・：；！？!?\])）｝」』】〉》ぁぃぅぇぉっゃゅょー…]/.test(line.text),
      ),
    );
    assert.ok(lines.every((line) => !/[([{（｛「『【〈《]$/.test(line.text)));
    if (title.startsWith('これは非常に長い')) {
      assert.equal(layout.truncated, true);
      assert.equal(layout.fontSize, 56);
      assert.equal(lines.length, 3);
      assert.match(lines.at(-1).text, /…$/);
    }
  }
});
